# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: false

# Setup
title:            AZubieta Blog
tagline:          'Software Development and OpenSource'
description:      "Hi. I\'m a software developer from Cuba. I have a passion for software architecture and love to create for GNU/Linux."
url:              https://azubieta.net
baseurl:          /

author:
  name:           'Alexis Lopez Zubieta'
  twitter:        'https://twitter.com/azubieta90'
  github:         'https://github.com/azubieta/'
  mastodom:       '@azubieta@fosstodon.org'

paginate:         5


plugins:
  - jekyll-paginate
  - jekyll-feed

gems:
  - jekyll-octicons
