# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            CodeOn
tagline:          'Software Development and OpenSource'
description:      "I\'m Alexis Lopez, a Cuban software developer and this is my blog. Hope you find it useful. Thanks for reading!"
url:              http://azubieta.net
baseurl:          /

author:
  name:           'Alexis Lopez Zubieta'
  url:            https://twitter.com/azubieta90

paginate:         5

# Custom vars
version:          2.1.0

#github:
#repo: https://github.com/poole/hyde

relative_permalinks: false

plugins: [jekyll-paginate]