# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: CodeOn
email: contact@azubieta.net
description: > # this means to ignore newlines until "baseurl:"
  This an place do talk about software development, GNU/Linux, AppImages, Desktop Environments and more.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://azubieta.net" # the base hostname & protocol for your site
twitter_username: azubieta90
github_username:  azubieta

# Build settings
markdown: kramdown
kramdown:
  input: GFM

# Third-party services
# just leave someone empty to disable it
# google_analytics: 
disqus_shortname: azubieta-net

# used this for post_excerpt at index_page
excerpt_separator: <!--description-->
