title: Code Adventures
author: Alexis Lopez Zubieta
email: contact@azubieta.net
description: > # this means to ignore newlines until "show_exerpts:"
  This an place do talk about software development, GNU/Linux, AppImages,
  Desktop Environments and more.
show_excerpts: true # set to true to show excerpts on the homepage

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
sass:
  sass_dir: _sass
plainwhite:
  name: Alexis Lopez
  tagline: Software Developer
  date_format: "%b %-d, %Y"
  sitemap: true # set to true to generate sitemap.xml content
  disqus_shortname: azubieta-net
  # generate social links in footer
  social_links:
    twitter: azubieta90
    github:  azubieta
    telegram: azubieta
    # Mastodon instances
    mastodon:
     - username: azubieta
       instance: fosstodon.org

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
theme: plainwhite

font-awesome:
  assets: true

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-font-awesome-sass